[project]
name = "bsky-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "atproto>=0.0.63",
    "jpholiday>=1.0.3",
]
