name: Bluesky bot

on:
  schedule:
    - cron: '0 3 * * *'     # 定時実行（UTC）
  workflow_dispatch:        # 手動実行も可能

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup dependencies
        run: uv sync

      - name: Run python script for Bluesky bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
        run: |
          uv run main.py
