name: Bluesky bot

on:
  schedule:
    - cron: '0 * * * *'     # 毎時実行（UTC）
  workflow_dispatch:        # 手動実行も可能

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      # Setup dependencies
      - name: Sync dependencies
        run: uv sync

      # Run python script to change notifications status
      - name: Post message to Bluesky
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
        run: |
          uv run main.py
